### ISSUE TITLE
[Bug]: NotebookSizes using Partial Cores Causes Mismatches

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you set a Notebook size to have partials... something like this:
```
    - name: XSmall
      resources:
        limits:
          cpu: "0.5"
          memory: 500Mi
        requests:
          cpu: "0.1"
          memory: 100Mi
```
You end up having a very specific setting. This would work out fine if K8s kept that... but they instead translate to mili-cores. eg `cpu: 0.5` notebook size shows up as `cpu: 500m` on the resource container. Thus the matching in the table never works out.

![image](https://user-images.githubusercontent.com/8126518/224819063-b2a759a6-b364-422e-9cb5-e0708c8c3bb9.png)

### Expected Behavior

For the Container Size field to find the proper related size in the config.

### Steps To Reproduce

1. Add the snippet to your notebook sizes array in the odh dashboard config (see the current behaviour section)
2. Create a workbench with it in DS Projects
3. Look at the table row result

### Workaround (if any)

Make the NotebookSize the lowest form it can be.

### Open Data Hub Version

```yml
ODH Dashboard: v2.8.0
```

### Anything else

You should be able to use the existing value units code found in [utilities/valueUnits.ts](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/utilities/valueUnits.ts)
