### ISSUE TITLE
[Feature Request]: Rework Feature Flags

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1108]
### Feature description

Our DashboardConfig is v1alpha1. I recommend we change that to v1alpha2 and rework the way our feature flags are stored.

We want to go to a highly customized structure of feature flags so things can be picked and chosen to be turned on / off.

I recommend something like:

```yaml
spec:
  features:
    # ...other flags
    projects:
      enabled: boolean
      permissions: boolean
    modelServing:
      enabled: boolean
      customRuntimes: boolean
      inferenceMetrics:
        performance: boolean
        bias: boolean
      runtimeMetrics:
        performance: boolean
      overrideMetricsNamespace: string # we'd need to change the backing logic for this -- this will be another issue
```
(see https://github.com/opendatahub-io/odh-dashboard/issues/1109 for more on metric namespace) 

There are features that are built on others -- and I think we need to look at tying them together. True here and False there, that could mean they are both False because features are dependant on each other. 

We also need to talk about how features are just not going to work without other unrelated but tied in features. Projects are a huge basis of what we are doing going forward. If projects are disabled -- what then?

### Describe alternatives you've considered

We keep what we have and it grows out of control slowly as we add more features related to each other.
