### ISSUE TITLE
Sync Data with Elyra Notebooks

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1121]
We will need to supply data to the Elyra notebooks.

We need to associate a secret (updated values included) every time the Notebooks are enabled or created -- once the Pipeline Operator is installed in the namespace.

Likely will be this structure...
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: ds-pipeline-config
type: Opaque
stringData: 
  odh_dsp.json: |-
   {
     "display_name": "ODH_DSP",
     "metadata": {
        "tags": [],
        "display_name": "ODH_DSP",
        "engine": "Tekton",
        "auth_type": "EXISTING_BEARER_TOKEN",
        "api_endpoint": "<data-science-pipeline-server-endpoint>", # our api url
        "cos_auth_type": "USER_CREDENTIALS",
        # unfurl the data connection secret that is associated to the DS Pipeline Server
        "cos_endpoint": "<storage-endpoint>",
        "cos_bucket": "default",
        "cos_username": "<aws-access-key-id>",
        "cos_password": "<aws-secret-access-key>",
        "runtime_type": "KUBEFLOW_PIPELINES"
      },
      "schema_name": "kfp"
    }
```
