### ISSUE TITLE
[Feature Request]: Enable Model Serving route per Project

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1287]
### Feature description

As it right now, we are creating a `Route` object for every `InferenceService` instance we deploy in a Project. That can lead to serious performance issues.

We are working with the model serving team to adapt the controller for this specific scenario:

1. When a Serving Runtime is created in a namespace, the odh-model-controller will create a route with a deterministic name based on the namespace (project)
2. Each time we create a new inference service, it will add a path with a deterministic format if external route is enabled.
3. This logic will be available for both inferenceSErvices already deployed and new ones.
4. For existing inference services, the old route will be available in case it's being used for production.

**Comment by lucferbux** [comment]
@vconzola Just to have a confirmation in this tracker, we were fine on displaying a new route in the inference service right?

**Comment by lucferbux** [comment]
@VedantMahabaleshwarkar This is the dashboard tracker fo the feature. If you can share here the kdfef to start testing the feature would be super helpful. thanks in advance!

**Comment by vconzola** [comment]
@lucferbux Each model (inference service) still have a unique route+path (for both HTTP and gRPC), right? Or will they all be the same within a project?

**Comment by VedantMahabaleshwarkar** [comment]
kfdef to test odh-model-controller behavior today 
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        overlays:
          - odh-model-controller
        parameters:
          - name: monitoring-namespace
            value: opendatahub
        repoRef:
          name: manifests
          path: model-mesh
      name: model-mesh
    - kustomizeConfig:
        parameters:
          - name: deployment-namespace
            value: opendatahub
        repoRef:
          name: manifests
          path: modelmesh-monitoring
      name: modelmesh-monitoring
  repos:
    - name: manifests
      uri: 'https://github.com/VedantMahabaleshwarkar/odh-manifests/tarball/oneroute'
```
