### ISSUE TITLE
[Bug]: odh-admin Group entry not honored for data science project creation ability

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the most recent master-version of dashboard code (PR 800 based on master).

When logged into ODH Dashboard and going to Data Science Projects, I get the following message:

**No data science projects yet
To get started, ask your Open Data Hub admin for a data science project or launch a notebook with Jupyter.**

![Bildschirmfoto 2023-06-03 um 23 19 38](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/ee850990-7edb-4973-a18f-935d6ccfd04f)

Only the "Launch Jupyter" button is available.

The interesting thing is: I am logged in as a user that is in the group mentioned in OdhDashboardConfig odh-dashboard-config.

```
  groupsConfig:
    adminGroups: xxx-OpenShift-xxx-test-Admin-GS
```

Group Spec with my username I used to log in to odh dashboard.

```
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: xxx-OpenShift-xxx-test-Admin-GS
  labels:
    openshift.io/ldap.host: blabla.ch
..
users:
  - myusernameusedforodhlogin
```

That group has clusterrole admin for the dashboard namespace

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-xxx-OpenShift-xxx-test-Admin-GS
  namespace: opendatahubnamespaceiedashboardnamespace
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: xxx-OpenShift-xxx-test-Admin-GS
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
```

I am definitely a user with admin rights on the dashboard namespace .... I can do everything an admin is supposed to being able to do on Openshift. I am also in the group referenced under adminGroups at odh-dashboard-config. What more is necessary? Can it be that DS project creation only works for cluster-admins? 

Again, I can log into dashboard, that is all ok. Also, all other admin-level functionality, like setting default pvc sizes from gui or stopping notebooks in jupyter tile is working fine. The whole settings panel is visible.

### Expected Behavior

Being able to create data science projects when logged in as a user in a group with namespace-level admin rights in openshift and whose group is referenced in the dashboard config.

### Steps To Reproduce

OCP 4.10

Dashboard master code

### What browsers are you seeing the problem on?

Microsoft Edge

### Open Data Hub Version

```yml
latest manifests from master-branch of odh-dashboard.
```
