### ISSUE TITLE
[Bug]: Wrong validation of Serving Runtimes in Creation time

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

To check if an object in our template is a Serving Runtime we use this piece of code:

```typescript
export const isServingRuntimeKind = (obj: K8sResourceCommon): obj is ServingRuntimeKind =>
  obj.kind === 'ServingRuntime' &&
  obj.spec?.builtInAdapter !== undefined &&
  obj.spec?.containers !== undefined &&
  obj.spec?.supportedModelFormats !== undefined;
```

But `builtInAdapter` is not a mandatory field, we should remove it from validation.

### Expected Behavior

You can create a Serving Runtime without explicitly declaring `builtInAdapter`.

### Steps To Reproduce

1. Create a new Custom Serving Runtime with the spec bellow
2. Try to create a model server
3. See that it's failing

```
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    name: ovms-no-builtin
    opendatahub.io/disable-gpu: "true"
    openshift.io/display-name: OpenVINO Model Server No builtinAdapter
  labels:
    opendatahub.io/dashboard: "true"
  name: ovms
spec:
  containers:
    - args:
        - --port=8001
        - --rest_port=8888
        - --config_path=/models/model_config_list.json
        - --file_system_poll_wait_seconds=0
        - --grpc_bind_address=127.0.0.1
        - --rest_bind_address=127.0.0.1
      image: quay.io/opendatahub/openvino_model_server@sha256:20dbfbaf53d1afbd47c612d953984238cb0e207972ed544a5ea662c2404f276d
      name: ovms
      resources:
        limits:
          cpu: "0"
          memory: 0Gi
        requests:
          cpu: "0"
          memory: 0Gi
  grpcDataEndpoint: port:8001
  grpcEndpoint: port:8085
  multiModel: true
  protocolVersions:
    - grpc-v1
  replicas: 1
  supportedModelFormats:
    - autoSelect: true
      name: openvino_ir
      version: opset1
    - autoSelect: true
      name: onnx
      version: "1"
    - autoSelect: true
      name: tensorflow
      version: "2"

```

### Workaround (if any)

Add `builtInAdapter` in the spec
