### ISSUE TITLE
[Feature Request]: allow creating workbench envs from secrets

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1380]
### Feature description

Currently, data to be provided as env variables in notebooks is manually typed-in and then converted into a secret.

![Bildschirmfoto 2023-06-14 um 14 01 44](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/e911fdbc-58b6-4d60-8477-3827cdf57d6f)

```
apiVersion: v1
kind: Secret
metadata:
  name: accesskey-secret
type: Opaque
data:
  username: blabla
  password: blablapassword
```

There is the other way around, though, that is used much more often:

There are secrets in the namespace, be it with database connection strings or certain api keys, that we want to have available inside a running notebook via env variable. A secret can have multiple keys, such as username and password above. In that case, the container with the spec below would have two env vars from secret database-secret inside it

username
password

The mechanism for that on a notebook container level is envFrom in the container section

```
spec:
    containers:
    - env: 
      - name: ServiceBindingOperatorChangeTriggerEnvVar
        value: "31793"
        envFrom:
        - secretRef:
            name: database-secret
        - secretRef:
            name: accesskey-secret
```

I do not suggest odh dashboard create secrets (which is fine already), I am in addition suggesting using existing secrets, as often happens in corporate environments. The cluster admins are aware of which secrets they provide and create in a data science projects namespace. So having the values of those secrets available inside the container as env is ok.

@lucferbux Maybe your architects can give an opinion, also,
