### ISSUE TITLE
[Bug]: Expected arrow connections not appearing in DSP UI

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/odh-dashboard#1437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following pipeline does not show expected connections: 

![image](https://github.com/opendatahub-io/odh-dashboard/assets/10904967/edb973b8-a313-44a9-bced-a782aab6249e)

In KFP ui it looks like the following: 

![image](https://github.com/opendatahub-io/odh-dashboard/assets/10904967/e75cf151-c3f0-4f62-933f-dd4a9679d487)

The pipeline can be found here. 

<details> 

<summary>pipeline.yaml</summary>

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dedup-ray-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"compute-execution-params": [{"key":
      "artifacts/$PIPELINERUN/compute-execution-params/Output.tgz", "name":
      "compute-execution-params-Output", "path": "/tmp/outputs/Output/data"}],
      "start-ray-cluster": [{"key":
      "artifacts/$PIPELINERUN/start-ray-cluster/Output.tgz", "name":
      "start-ray-cluster-Output", "path": "/tmp/outputs/Output/data"}]}'
    tekton.dev/input_artifacts: '{"execute-ray-jobs": [{"name":
      "compute-execution-params-Output", "parent_task":
      "compute-execution-params"}, {"name": "start-ray-cluster-Output",
      "parent_task": "start-ray-cluster"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"cleanup-ray-cluster": [],
      "compute-execution-params": [["Output", "$(results.Output.path)"]],
      "execute-ray-jobs": [], "start-ray-cluster": [["Output",
      "$(results.Output.path)"]]}'
    sidecar.istio.io/inject: "false"
    tekton.dev/template: ""
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Pipeline to show how to
      use codeflare sdk to create Ray cluster and run dedup", "inputs":
      [{"default": "kfp-ray-dedup", "name": "name", "optional": true, "type":
      "String"}, {"default": "8", "name": "num_workers", "optional": true,
      "type": "String"}, {"default": "8", "name": "worker_cpu", "optional":
      true, "type": "String"}, {"default": "32", "name": "worker_memory",
      "optional": true, "type": "String"}, {"default": "0", "name":
      "worker_gpu", "optional": true, "type": "String"}, {"default": "1",
      "name": "wait_ready_tmout", "optional": true, "type": "String"},
      {"default": "100", "name": "wait_ready_retries", "optional": true, "type":
      "String"}, {"default": "1", "name": "print_tmout", "optional": true,
      "type": "String"}, {"default": "ray-dedup-template", "name":
      "template_cm", "optional": true, "type": "String"}, {"default":
      "quay.io/ibmdpdev/dedup-exact-ray:2.5.1-py310", "name": "image",
      "optional": true, "type": "String"}, {"default":
      "cos-optimal-llm-pile/blue-pile/0_internet/2_commoncrawl/ete=v0.2",
      "name": "input_path", "optional": true, "type": "String"}, {"default":
      "cos-optimal-llm-pile/boris_test/", "name": "output_path", "optional":
      true, "type": "String"}, {"default": "contents", "name": "content",
      "optional": true, "type": "String"}, {"default": "100", "name":
      "max_files", "optional": true, "type": "String"}, {"default": "5", "name":
      "n_sample", "optional": true, "type": "String"}, {"default": ".75",
      "name": "processor_cpu", "optional": true, "type": "String"}, {"default":
      ".5", "name": "hash_cpu", "optional": true, "type": "String"}], "name":
      "dedup-ray-pipeline"}'
  labels:
    pipelines.kubeflow.org/pipelinename: ""
    pipelines.kubeflow.org/generation: ""
spec:
  params:
    - name: content
      value: contents
    - name: hash_cpu
      value: ".5"
    - name: image
      value: quay.io/ibmdpdev/dedup-exact-ray:2.5.1-py310
    - name: input_path
      value: cos-optimal-llm-pile/blue-pile/0_internet/2_commoncrawl/ete=v0.2
    - name: max_files
      value: "100"
    - name: n_sample
      value: "5"
    - name: name
      value: kfp-ray-dedup
    - name: num_workers
      value: "8"
    - name: output_path
      value: cos-optimal-llm-pile/boris_test/
    - name: print_tmout
      value: "1"
    - name: processor_cpu
      value: ".75"
    - name: template_cm
      value: ray-dedup-template
    - name: wait_ready_retries
      value: "100"
    - name: wait_ready_tmout
      value: "1"
    - name: worker_cpu
      value: "8"
    - name: worker_gpu
      value: "0"
    - name: worker_memory
      value: "32"
  pipelineSpec:
    params:
      - name: content
        default: contents
      - name: hash_cpu
        default: ".5"
      - name: image
        default: quay.io/ibmdpdev/dedup-exact-ray:2.5.1-py310
      - name: input_path
        default: cos-optimal-llm-pile/blue-pile/0_internet/2_commoncrawl/ete=v0.2
      - name: max_files
        default: "100"
      - name: n_sample
        default: "5"
      - name: name
        default: kfp-ray-dedup
      - name: num_workers
        default: "8"
      - name: output_path
        default: cos-optimal-llm-pile/boris_test/
      - name: print_tmout
        default: "1"
      - name: processor_cpu
        default: ".75"
      - name: template_cm
        default: ray-dedup-template
      - name: wait_ready_retries
        default: "100"
      - name: wait_ready_tmout
        default: "1"
      - name: worker_cpu
        default: "8"
      - name: worker_gpu
        default: "0"
      - name: worker_memory
        default: "32"
    tasks:
      - name: compute-execution-params
        params:
          - name: content
            value: $(params.content)
          - name: hash_cpu
            value: $(params.hash_cpu)
          - name: input_path
            value: $(params.input_path)
          - name: max_files
            value: $(params.max_files)
          - name: n_sample
            value: $(params.n_sample)
          - name: num_workers
            value: $(params.num_workers)
          - name: processor_cpu
            value: $(params.processor_cpu)
          - name: worker_cpu
            value: $(params.worker_cpu)
          - name: worker_memory
            value: $(params.worker_memory)
        taskSpec:
          steps:
            - name: main
              args:
                - --num-workers
                - $(inputs.params.num_workers)
                - --worker-cpu
                - $(inputs.params.worker_cpu)
                - --worker-memory
                - $(inputs.params.worker_memory)
                - --input-path
                - $(inputs.params.input_path)
                - --content
                - $(inputs.params.content)
                - --n-sample
                - $(inputs.params.n_sample)
                - --max-files
                - $(inputs.params.max_files)
                - --processor-cpu
                - $(inputs.params.processor_cpu)
                - --hash-cpu
                - $(inputs.params.hash_cpu)
                - ----output-paths
                - $(results.Output.path)
              command:
                - sh
                - -ec
                - |
                  program_path=$(mktemp)
                  printf "%s" "$0" > "$program_path"
                  python3 -u "$program_path" "$@"
                - >
                  def compute_execution_params(num_workers,  # number of workers
                                               worker_cpu,  # number cpus per worker
                                               worker_memory,  # memory per worker
                                               # Dedup specific parameters
                                               input_path,  # data input directory
                                               content,  # name of the documents column
                                               n_sample,  # number of tables to sample
                                               max_files,  # maximum amount of files to process
                                               processor_cpu,  # Number of CPUs to do table processing
                                               hash_cpu  # Number of CPUs to do table processing
                                               ):
                      # required import
                      from pyarrow import fs
                      import pyarrow.parquet as pq

                      import random
                      import sys
                      import math
                      import json
                      import os

                      COS_URL = "https://s3.us-east.cloud-object-storage.appdomain.cloud"
                      EXECUTION_OF_KB_DOC = 0.00025
                      GB = 1024*1024*1024

                      def _credentials():
                          cos_key = os.getenv('COS_KEY', "")
                          cos_secret = os.getenv('COS_SECRET', "")
                          if cos_key == "" or cos_secret == "":
                              print("Failed to get cos credentials")
                              sys.exit(1)
                          return cos_key, cos_secret

                      def _sample_table_data(cos_key, cos_secret, input_path, max_files, n_samples):

                          # Create fs
                          s3 = fs.S3FileSystem(access_key=cos_key, secret_key=cos_secret, request_timeout=20, connect_timeout=20,
                                               retry_strategy=fs.AwsStandardS3RetryStrategy(max_attempts=20),
                                               endpoint_override=COS_URL)
                          # Get files list
                          path_list = [file.path for
                                       file in s3.get_file_info(fs.FileSelector(input_path)) if file.path.endswith(".parquet")]
                          # Cap the amount of files if required
                          if max_files > 0:
                              cap = min(len(path_list), max_files)
                              path_list = path_list[:cap]
                          print(f"Number of s3 files is {len(path_list)}")

                          # Pick files to sample
                          if len(path_list) > n_samples:
                              # Pick files at random
                              files = [int(random.random()*len(path_list)) for _ in range(n_samples)]
                          else:
                              # use all existing files
                              files = range(len(path_list))
                          print(f"Using files {files} to sample data")

                          # Read table and compute number of docs and sizes
                          number_of_docs = []
                          table_sizes = []
                          for f in files:
                              f_name = path_list[f]
                              table = pq.read_table(f_name, filesystem=s3, columns=[content])
                              number_of_docs.append(table.num_rows)
                              table_sizes.append(sys.getsizeof(table))

                          # compute averages
                          av_number_docs = sum(number_of_docs) / len(files)
                          av_table_size = sum(table_sizes) / len(files) / GB
                          av_doc_size = av_table_size * GB / av_number_docs / 1024
                          print(f"average number of docs {av_number_docs}, average table size {av_table_size} GB, "
                                f"average doc size {av_doc_size} kB")

                          # compute number of docs
                          number_of_docs = av_number_docs * len(path_list)
                          print(f"Estimated number of docs {number_of_docs}")
                          return av_table_size, av_doc_size, number_of_docs

                      # get credentials
                      cos_key, cos_secret = _credentials()

                      # sample input data
                      av_table_size, av_doc_size, number_of_docs = _sample_table_data(
                          cos_key=cos_key, cos_secret=cos_secret, input_path=input_path, max_files=int(max_files),
                          n_samples=int(n_sample))
                      n_hashes = math.ceil(number_of_docs * 32 / GB)
                      print(f"Estimated Required hashes {n_hashes}")

                      # Validate cluster size
                      cluster_cpu = int(num_workers) * int(worker_cpu) * .85
                      cluster_mem = int(num_workers) * int(worker_memory) * .85
                      required_hash_cpu = n_hashes * float(hash_cpu)
                      required_hash_mem = n_hashes * 2
                      if required_hash_cpu > cluster_cpu or required_hash_mem > cluster_mem:
                          print(f"Cluster is too small - hashes required cpus {required_hash_cpu}; "
                                f"hashes required memory {required_hash_mem}")
                          sys.exit(1)
                      # Define number of workers
                      n_workers = int((cluster_cpu - required_hash_cpu)/float(processor_cpu))
                      print(f"Number of workers - {n_workers}")
                      if n_workers < 5:
                          print(f"Cluster is too small - estimated number of workers {n_workers}")
                          sys.exit(1)
                      r_mem = required_hash_mem * 2 + av_table_size * 4 * n_workers
                      print(f"Required execution memory {r_mem} GB")
                      if r_mem > cluster_mem:
                          print(f"Not enough memory to run de duping, required {r_mem}, available {cluster_mem}")
                          print(f"Try to increase the size of the cluster or increase size of the cpu per worker")
                          sys.exit(1)
                      print(f"Projected execution time {EXECUTION_OF_KB_DOC * av_doc_size * number_of_docs / n_workers / 60} min")
                      return json.dumps({'workers': n_workers, 'hashes': n_hashes})

                  def _serialize_str(str_value: str) -> str:
                      if not isinstance(str_value, str):
                          raise TypeError('Value "{}" has type "{}" instead of str.'.format(
                              str(str_value), str(type(str_value))))
                      return str_value

                  import argparse

                  _parser = argparse.ArgumentParser(prog='Compute execution params', description='')

                  _parser.add_argument("--num-workers", dest="num_workers", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--worker-cpu", dest="worker_cpu", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--worker-memory", dest="worker_memory", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--input-path", dest="input_path", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--content", dest="content", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--n-sample", dest="n_sample", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--max-files", dest="max_files", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--processor-cpu", dest="processor_cpu", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--hash-cpu", dest="hash_cpu", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("----output-paths", dest="_output_paths", type=str, nargs=1)

                  _parsed_args = vars(_parser.parse_args())

                  _output_files = _parsed_args.pop("_output_paths", [])


                  _outputs = compute_execution_params(**_parsed_args)


                  _outputs = [_outputs]


                  _output_serializers = [
                      _serialize_str,

                  ]


                  import os

                  for idx, output_file in enumerate(_output_files):
                      try:
                          os.makedirs(os.path.dirname(output_file))
                      except OSError:
                          pass
                      with open(output_file, 'w') as f:
                          f.write(_output_serializers[idx](_outputs[idx]))
              env:
                - name: COS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: cos-key
                      name: cos-access
                - name: COS_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: cos-secret
                      name: cos-access
              image: quay.io/ibmdpdev/kfp-oc:2.5.1-py310
              imagePullPolicy: Always
          params:
            - name: content
            - name: hash_cpu
            - name: input_path
            - name: max_files
            - name: n_sample
            - name: num_workers
            - name: processor_cpu
            - name: worker_cpu
            - name: worker_memory
          results:
            - name: Output
              type: string
              description: /tmp/outputs/Output/data
          metadata:
            labels:
              pipelines.kubeflow.org/cache_enabled: "true"
            annotations:
              pipelines.kubeflow.org/component_spec_digest: '{"name": "Compute execution
                params", "outputs": [{"name": "Output", "type": "String"}],
                "version": "Compute execution
                params@sha256=441f924ac97baa98300019ea5bc3a1fb109d4c2f80de356fde7984b9505e1c98"}'
      - name: start-ray-cluster
        params:
          - name: image
            value: $(params.image)
          - name: name
            value: $(params.name)
          - name: num_workers
            value: $(params.num_workers)
          - name: template_cm
            value: $(params.template_cm)
          - name: worker_cpu
            value: $(params.worker_cpu)
          - name: worker_gpu
            value: $(params.worker_gpu)
          - name: worker_memory
            value: $(params.worker_memory)
        taskSpec:
          steps:
            - name: main
              args:
                - --name
                - $(inputs.params.name)
                - --num-workers
                - $(inputs.params.num_workers)
                - --worker-cpu
                - $(inputs.params.worker_cpu)
                - --worker-memory
                - $(inputs.params.worker_memory)
                - --worker-gpu
                - $(inputs.params.worker_gpu)
                - --image
                - $(inputs.params.image)
                - ----output-paths
                - $(results.Output.path)
              command:
                - sh
                - -ec
                - |
                  program_path=$(mktemp)
                  printf "%s" "$0" > "$program_path"
                  python3 -u "$program_path" "$@"
                - >
                  def start_ray_cluster(
                          name,          # name of Ray cluster
                          num_workers,   # number of workers
                          worker_cpu,    # number cpus per worker
                          worker_memory, # memory per worker
                          worker_gpu,    # number of gpus per worker
                          image,         # image for Ray cluster
                  ):
                      # Imports
                      import os
                      import sys
                      import time

                      import ray
                      from codeflare_sdk.cluster.auth import TokenAuthentication
                      from codeflare_sdk.cluster.cluster import Cluster, ClusterConfiguration

                      # Ray routine to get the amount of nodes
                      @ray.remote
                      def get_cluster_nodes():
                          nodes = ray.nodes()
                          nnodes = -1
                          for n in nodes:
                              if n["alive"]:
                                  nnodes = nnodes + 1
                          return nnodes

                      # get current namespace
                      ns = os.getenv("NAMESPACE", "default")
                      # change the current directory to ensure that we can write
                      os.chdir("/tmp")
                      print(f"Executing in namespace {ns}, current working directory is {os.getcwd()}")

                      # Create authentication object for oc user permissions
                      with open("/var/run/secrets/kubernetes.io/serviceaccount/token", "r") as file:
                          token = file.read().rstrip()
                      auth = TokenAuthentication(token=token, server="https://kubernetes.default:443", skip_tls=True)
                      try:
                          auth.login()
                      except Exception as e:
                          print(f"Failed to log into openshift cluster, error {e}. Please check token/server values provided")
                          sys.exit(1)
                      print("successfully logged in")

                      # Create and configure our cluster object (and appwrapper)
                      cluster = Cluster(
                          ClusterConfiguration(
                              name=name,
                              namespace=ns,
                              min_worker=int(num_workers),
                              max_worker=int(num_workers),
                              min_cpus=int(worker_cpu),
                              max_cpus=int(worker_cpu),
                              min_memory=int(worker_memory),
                              max_memory=int(worker_memory),
                              gpu=int(worker_gpu),
                              image=image,
                              template="/templates/ray_template.yaml",
                              instascale=False,
                          )
                      )
                      print(f"Configuration for Ray cluster {name} in namespace {ns} is created")

                      try:
                          # bring up the cluster
                          cluster.up()
                          print(f"Creating Ray cluster {name} in namespace {ns}...")

                          # and wait for it being up
                          cluster.wait_ready()
                          rc = cluster.details(print_to_console=False)
                          print("Ray cluster is ready")
                          print(rc)

                          # Get cluster connection point for job submission
                          ray_dashboard_uri = cluster.cluster_dashboard_uri()
                          ray_cluster_uri = cluster.cluster_uri()
                          print(f"Ray_cluster is at {ray_cluster_uri}")
                          print(f"Ray_cluster dashboard is at {ray_dashboard_uri}")

                          # wait to ensure that cluster is really up. Without this we can get occasional 503 error
                          time.sleep(5)

                          # make sure all the nodes are up
                          ray.init(address=f"{ray_cluster_uri}")
                          running = 0
                          while running < int(num_workers):
                              running = ray.get(get_cluster_nodes.remote())
                              print(f"{running} nodes are currently available")
                              time.sleep(1)
                          ray.shutdown()
                          return ray_dashboard_uri
                      except Exception as e:
                          print(f"Failed to init Ray cluster, error {e}")
                          sys.exit(1)

                  def _serialize_str(str_value: str) -> str:
                      if not isinstance(str_value, str):
                          raise TypeError('Value "{}" has type "{}" instead of str.'.format(
                              str(str_value), str(type(str_value))))
                      return str_value

                  import argparse

                  _parser = argparse.ArgumentParser(prog='Start ray cluster', description='')

                  _parser.add_argument("--name", dest="name", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--num-workers", dest="num_workers", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--worker-cpu", dest="worker_cpu", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--worker-memory", dest="worker_memory", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--worker-gpu", dest="worker_gpu", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--image", dest="image", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("----output-paths", dest="_output_paths", type=str, nargs=1)

                  _parsed_args = vars(_parser.parse_args())

                  _output_files = _parsed_args.pop("_output_paths", [])


                  _outputs = start_ray_cluster(**_parsed_args)


                  _outputs = [_outputs]


                  _output_serializers = [
                      _serialize_str,

                  ]


                  import os

                  for idx, output_file in enumerate(_output_files):
                      try:
                          os.makedirs(os.path.dirname(output_file))
                      except OSError:
                          pass
                      with open(output_file, 'w') as f:
                          f.write(_output_serializers[idx](_outputs[idx]))
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: quay.io/ibmdpdev/kfp-oc:2.5.1-py310
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /templates
                  name: templates
          params:
            - name: image
            - name: name
            - name: num_workers
            - name: template_cm
            - name: worker_cpu
            - name: worker_gpu
            - name: worker_memory
          results:
            - name: Output
              type: string
              description: /tmp/outputs/Output/data
          volumes:
            - configMap:
                name: $(inputs.params.template_cm)
              name: templates
          metadata:
            labels:
              pipelines.kubeflow.org/cache_enabled: "true"
            annotations:
              pipelines.kubeflow.org/component_spec_digest: '{"name": "Start ray cluster",
                "outputs": [{"name": "Output", "type": "String"}], "version":
                "Start ray
                cluster@sha256=aa5e200274d1b535332c459aaa022a0209f81336c1ea303b319be92deb2b9347"}'
              pipelines.kubeflow.org/max_cache_staleness: P0D
        runAfter:
          - compute-execution-params
      - name: execute-ray-jobs
        params:
          - name: compute-execution-params-Output
            value: $(tasks.compute-execution-params.results.Output)
          - name: content
            value: $(params.content)
          - name: hash_cpu
            value: $(params.hash_cpu)
          - name: input_path
            value: $(params.input_path)
          - name: max_files
            value: $(params.max_files)
          - name: output_path
            value: $(params.output_path)
          - name: print_tmout
            value: $(params.print_tmout)
          - name: processor_cpu
            value: $(params.processor_cpu)
          - name: start-ray-cluster-Output
            value: $(tasks.start-ray-cluster.results.Output)
          - name: wait_ready_retries
            value: $(params.wait_ready_retries)
          - name: wait_ready_tmout
            value: $(params.wait_ready_tmout)
        taskSpec:
          steps:
            - name: main
              args:
                - --ray-dashboard-uri
                - $(inputs.params.start-ray-cluster-Output)
                - --wait-ready-tmout
                - $(inputs.params.wait_ready_tmout)
                - --wait-ready-retries
                - $(inputs.params.wait_ready_retries)
                - --print-tmout
                - $(inputs.params.print_tmout)
                - --input-path
                - $(inputs.params.input_path)
                - --output-path
                - $(inputs.params.output_path)
                - --content
                - $(inputs.params.content)
                - --max-files
                - $(inputs.params.max_files)
                - --processor-cpu
                - $(inputs.params.processor_cpu)
                - --hash-cpu
                - $(inputs.params.hash_cpu)
                - --execution-params
                - $(inputs.params.compute-execution-params-Output)
              command:
                - sh
                - -ec
                - |
                  program_path=$(mktemp)
                  printf "%s" "$0" > "$program_path"
                  python3 -u "$program_path" "$@"
                - >
                  def execute_ray_jobs(
                          ray_dashboard_uri, # ray dashboard uri
                          wait_ready_tmout,  # wait tmout for job ready
                          wait_ready_retries,# wait retries for job ready
                          print_tmout,       # print timeout
                          # Dedup specific parameters
                          input_path,        # data input directory
                          output_path,       # data output directory
                          content,           # name of the documents column
                          max_files,         # maximum amount of files to process
                          processor_cpu,     # Number of CPUs to do table processing
                          hash_cpu,          # Number of CPUs to do table processing
                          execution_params   # config parameters computed in initial step
                  ):
                      # required imports
                      from pyarrow import fs
                      import json
                      import sys
                      import time
                      import os

                      import requests
                      from ray.job_submission import JobStatus

                      COS_URL = "https://s3.us-east.cloud-object-storage.appdomain.cloud"

                      # Get credentials
                      def _credentials():
                          cos_key = os.getenv('COS_KEY', "")
                          cos_secret = os.getenv('COS_SECRET', "")
                          if cos_key == "" or cos_secret == "":
                              print("Failed to get cos credentials")
                              sys.exit(1)
                          return cos_key, cos_secret

                      # Get job status
                      def _get_job_status(ray_dashboard_uri, job_id):
                          resp = requests.get(f"{ray_dashboard_uri}/api/jobs/{job_id}")
                          if resp.status_code == 200:
                              rst = json.loads(resp.text)
                              return rst["status"]
                          else:
                              print(f"Getting job execution status failed, code {resp.status_code}")
                              return JobStatus.PENDING

                      # Get job log
                      def _get_job_log(ray_dashboard_uri, job_id):
                          resp = requests.get(f"{ray_dashboard_uri}/api/jobs/{job_id}/logs")
                          if resp.status_code == 200:
                              rst = json.loads(resp.text)
                              return rst["logs"]
                          else:
                              print(f"Getting job execution log failed, code {resp.status_code}")
                              return ''

                      # Print job log
                      def _print_log(log, previous_log_len):
                          l_to_print = log[previous_log_len:]
                          if len(l_to_print) > 0:
                              print(log)

                      # Get parameters necessary for submitting
                      execution_params = json.loads(execution_params)
                      cos_key, cos_secret = _credentials()

                      #Submitting job
                      job_id = None
                      try:
                          resp = requests.post(
                              f"{ray_dashboard_uri}/api/jobs/",
                              json={
                                  "entrypoint": f"python dedup_exact_files_wf.py --input_path={input_path} --output_path={output_path} "
                                                f"--content={content} --max_files={int(max_files)} --worker_cpu={float(processor_cpu)} "
                                                f"--hash_cpu={float(hash_cpu)} --num_hashes={execution_params['hashes']} "
                                                f"--num_workers={execution_params['workers']}",
                                  "runtime_env": {'env_vars': {'COS_KEY': cos_key, 'COS_SECRET': cos_secret}}
                              }
                          )
                          if resp.status_code == 200:
                              rst = json.loads(resp.text)
                              job_id = rst["job_id"]
                              print(f"Submitted job to Ray with the id: {job_id}")
                          else:
                              print(f"Failed to submitted job to Ray, code : {resp.status_code}")

                      except Exception as e:
                          print(f"Failed to submit job to Ray cluster, error {e}")
                          sys.exit(1)

                      # Waiting job to start
                      status = JobStatus.PENDING
                      tries = 0
                      try:
                          while status != JobStatus.RUNNING:
                              tries = tries + 1
                              status = _get_job_status(ray_dashboard_uri, job_id)
                              if status in {JobStatus.STOPPED, JobStatus.SUCCEEDED, JobStatus.FAILED}:
                                  break
                              if tries >= int(wait_ready_retries):
                                  print(f"Failed to get job success status in {int(wait_ready_retries)} tries")
                                  sys.exit(1)
                              time.sleep(int(wait_ready_tmout))
                          print(f"Job execution status is {status}")

                          # while job is running get job's log
                          previous_log_len = 0
                          while status == JobStatus.RUNNING:
                              log = _get_job_log(ray_dashboard_uri, job_id)
                              _print_log(log, previous_log_len)
                              previous_log_len = len(log)
                              time.sleep(int(print_tmout))
                              # Update status
                              status = _get_job_status(ray_dashboard_uri, job_id)

                          # print final log and status
                          flog = _get_job_log(ray_dashboard_uri, job_id)
                          _print_log(flog, previous_log_len)
                          print(f"Job execution status is {status}")

                          # Save the log to S3
                          s3 = fs.S3FileSystem(access_key=cos_key, secret_key=cos_secret, request_timeout=20, connect_timeout=20,
                                               retry_strategy=fs.AwsStandardS3RetryStrategy(max_attempts=20),endpoint_override=COS_URL)
                          with s3.open_output_stream(f"{output_path}execution.log") as stream:
                              stream.write(bytes(flog, 'UTF-8'))

                      except Exception as e:
                          print(f"Failed to get Ray job execution result, error {e}")
                          sys.exit(1)

                  import argparse

                  _parser = argparse.ArgumentParser(prog='Execute ray jobs', description='')

                  _parser.add_argument("--ray-dashboard-uri", dest="ray_dashboard_uri", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--wait-ready-tmout", dest="wait_ready_tmout", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--wait-ready-retries", dest="wait_ready_retries", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--print-tmout", dest="print_tmout", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--input-path", dest="input_path", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--output-path", dest="output_path", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--content", dest="content", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--max-files", dest="max_files", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--processor-cpu", dest="processor_cpu", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--hash-cpu", dest="hash_cpu", type=str, required=True, default=argparse.SUPPRESS)

                  _parser.add_argument("--execution-params", dest="execution_params", type=str, required=True, default=argparse.SUPPRESS)

                  _parsed_args = vars(_parser.parse_args())


                  _outputs = execute_ray_jobs(**_parsed_args)
              env:
                - name: COS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: cos-key
                      name: cos-access
                - name: COS_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: cos-secret
                      name: cos-access
              image: quay.io/ibmdpdev/kfp-oc:2.5.1-py310
              imagePullPolicy: Always
          params:
            - name: compute-execution-params-Output
            - name: content
            - name: hash_cpu
            - name: input_path
            - name: max_files
            - name: output_path
            - name: print_tmout
            - name: processor_cpu
            - name: start-ray-cluster-Output
            - name: wait_ready_retries
            - name: wait_ready_tmout
          metadata:
            labels:
              pipelines.kubeflow.org/cache_enabled: "true"
            annotations:
              pipelines.kubeflow.org/component_spec_digest: '{"name": "Execute ray jobs",
                "outputs": [], "version": "Execute ray
                jobs@sha256=bbf2878b3121c17550fbf97e668e66f7c733112b15ba468dbbdfbe942fb5f36a"}'
              pipelines.kubeflow.org/max_cache_staleness: P0D
    finally:
      - name: cleanup-ray-cluster
        params:
          - name: name
            value: $(params.name)
        taskSpec:
          steps:
            - name: main
              args:
                - --name
                - $(inputs.params.name)
              command:
                - sh
                - -ec
                - |
                  program_path=$(mktemp)
                  printf "%s" "$0" > "$program_path"
                  python3 -u "$program_path" "$@"
                - >
                  def cleanup_ray_cluster(
                          name,  # name of Ray cluster
                  ):
                      # Required imports
                      import os
                      import sys
                      from codeflare_sdk.cluster.auth import TokenAuthentication
                      from codeflare_sdk.cluster.cluster import Cluster, ClusterConfiguration

                      # get current namespace
                      ns = os.getenv("NAMESPACE", "default")
                      # change the current directory to ensure that we can write
                      os.chdir("/tmp")
                      print(f"Executing in namespace {ns}, current working directory is {os.getcwd()}")

                      # Create authentication object for oc user permissions
                      with open("/var/run/secrets/kubernetes.io/serviceaccount/token", "r") as file:
                          token = file.read().rstrip()
                      auth = TokenAuthentication(token=token, server="https://kubernetes.default:443", skip_tls=True)
                      try:
                          auth.login()
                      except Exception as e:
                          print(f"Failed to log into openshift cluster, error {e}. Please check token/server values provided")
                          sys.exit(1)
                      print("successfully logged in")
                      # Create and configure our cluster object (and appwrapper)
                      cluster = Cluster(
                          ClusterConfiguration(
                              name=name,
                              namespace=ns,
                          )
                      )
                      print(f"Configuration for Ray cluster {name} in namespace {ns} is created")
                      # delete cluster
                      print("All done. Cleaning up")
                      try:
                          cluster.down()
                      except Exception as e:
                          print(f"Failed to down the Ray cluster, error {e}. Please check that the {name} appwrapper is removed")

                  import argparse

                  _parser = argparse.ArgumentParser(prog='Cleanup ray cluster', description='')

                  _parser.add_argument("--name", dest="name", type=str, required=True, default=argparse.SUPPRESS)

                  _parsed_args = vars(_parser.parse_args())


                  _outputs = cleanup_ray_cluster(**_parsed_args)
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: quay.io/ibmdpdev/kfp-oc:2.5.1-py310
              imagePullPolicy: Always
          params:
            - name: name
          metadata:
            labels:
              pipelines.kubeflow.org/cache_enabled: "true"
            annotations:
              pipelines.kubeflow.org/component_spec_digest: '{"name": "Cleanup ray cluster",
                "outputs": [], "version": "Cleanup ray
                cluster@sha256=d0289f79abcf5240c250d7b8cffead358d6731a59c31c42b662653591da301a1"}'
  podTemplate:
    imagePullSecrets:
      - name: quay

```

</details>

### Expected Behavior

Visuals should match kfp - ui

Three elements seem to be missing: 

1. from `compute-execution-params` -> `execute-ray-jobs` 
2. `start-ray-cluster` -> `execute-ray-jobs` 
3. the exit handler should also show, `onExit - cleanup-ray-cluster`

### Steps To Reproduce

Create pipeline provided above, and compare visuals to kfp ui to see differences. 

### Workaround (if any)

none

### What browsers are you seeing the problem on?

Firefox

### Open Data Hub Version

```yml
v1.7
```
