### ISSUE TITLE
[Bug]: OOTB model serving framework descriptions are not intuitive

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1458]
### Feature description

When deploying a model within projects, the Ui has a field for 'Model framework'. The options in this field are not intuitive. The OOTB option names should be modified. 

Options are:

"openvino_ir - opset1" - not sure what this is, but not intuitive
"onnx - 1" - should probably be capitalized "ONNX", do we need the '-1'? 

### Anything else?

This UI is generated by these fields:

```yaml
supportedModelFormats:
  - autoSelect: true
    name: openvino_ir
    version: opset1
  - autoSelect: true
    name: onnx
    version: '1'
```
