### ISSUE TITLE
[Bug]: manifests bases notation on kustomization.yaml deprecated and not compatible with labelTransformer

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I wanted to add some more labels with a labelTransformer to the deployment labels and pod template labels of odh dashboard. This is often done in environments where scanning tools make an inventory of what is deployed and what the lifecycle looks like.

```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  mycompany.com/appname: dataanalysis
  version: 1.6.0
  mycompany.com/tenant: MTCLUSTER
  mycompany.com/environment: TST
  mycompany.com/appdescription: "RedHat_Open_Data_Hub_for_Machine_Learning"
  mycompany.com/Contact: "Max.Operator"
  mycompany.com/Contact2: "Pauline.Operator"
  mycompany.com/capability: "Innovation_and_Technology_Management"
  mycompany.com/customer: internal
  mycompany.com/techplatform: OCP4TST.MYCOMINTRA.COM
fieldSpecs:
  - path: metadata/labels
    kind: Deployment
    create: true
  - path: spec/template/metadata/labels
    kind: Deployment
    create: true
```

We usually add a tranformer section under resources in kustmization.yaml for that purpose and it is working fine for all components, except odh dashboard.

```
...
  - fetch-builds-and-images.rbac.yaml
  - image-puller.clusterrolebinding.yaml
  - model-serving-role.yaml
  - model-serving-role-binding.yaml
transformers:
  - deploymentLabelTransformer.yaml
```

### Expected Behavior

So my attention came to the [use of bases](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/kustomization.yaml#L6) in your manifests. I don't recall the exact documentation, but bases has been deprecated for a long time. It still works, but the recommendation is to put bases under resources.

After I removed bases and moved the referenced directories to resources, the labels adding worked fine.
Also, but that is just cosmetic, I indented two spaces all references.

@lucferbux @andrewballantyne Can you remove bases and move it to resources, please, like that:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
  - ../apps
  - ../modelserving
  - role.yaml
  - cluster-role.yaml
  - service-account.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - auth-delegator.clusterrolebinding.yaml
  - cluster-monitoring-role-binding.yaml
  - deployment.yaml
  - routes.yaml
  - service.yaml
  - oauth.secret.yaml
  - fetch-builds-and-images.rbac.yaml
  - image-puller.clusterrolebinding.yaml
  - model-serving-role.yaml
  - model-serving-role-binding.yaml
```

This works fine when I do it on our cluster like this. Meaning the ovms and ovms-cpu templates, plus the OdhAplication, OdhQuickstart, and OdhDocument instances that are referenced via 

resources:
  - ../apps
  - ../modelserving

are applied correctly. Plus, I can now see my custom labels on dashboard deployment and pods also :-)

### Open Data Hub Version

```yml
1.6.0
```
