### ISSUE TITLE
[Feature Request]: use sha256 digest values of images in odh-manifests non-master branch

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1470]
### Feature description

To be compatible with on-prem restricted network environment installs, image references need to be in sha256 digest format, not tag format. In any master or version branch of odh-manifests.

This applies, for odh dashboard recipes, mostly to the images section in kustomization.yaml

https://github.com/opendatahub-io/odh-manifests/blob/v1.7/odh-dashboard/base/kustomization.yaml#L25

i.e. instead of

```
images:
- name: odh-dashboard
  newName: quay.io/opendatahub/odh-dashboard
  newTag: v2.11.0
- name: oauth-proxy
  newName: registry.redhat.io/openshift4/ose-oauth-proxy
  newTag: v4.8
```

use the following format, yaml comment suggested for readability for humans :-)
digests are for illustration only.

```
images:
- name: odh-dashboard
  # quay.io/opendatahub/odh-dashboard:v2.11.0
  newName: quay.io/opendatahub/odh-dashboard
  digest: sha256:a2dabd2c272d7e9093d7f88d50c517c03742b97c348e0b772a9e813fd7e07d47
- name: oauth-proxy
  # registry.redhat.io/openshift4/ose-oauth-proxy:v4.10
  newName: registry.redhat.io/openshift4/ose-oauth-proxy
  digest: sha256:4d5687c6c9216e294d25c6b095f5f4b7ff96e005326fff3303bda7760e012d5b
```

@Jooho what do you think? Would a github action to scan for all images sections in odh manifests be the best way to handle this, updating to the digest-format, or should we leave this to the maintainers?

Also, sometimes, there are also program args, like for odh notebook controller, that need to be in sha256 digest format, like at https://github.com/opendatahub-io/odh-manifests/blob/master/odh-notebook-controller/odh-notebook-controller/manager/manager.yaml#L28 which are still in tag format.

### Describe alternatives you've considered

There is no way around digest format for on-prem and exact references to images.
