### ISSUE TITLE
[Bug]: Pipelines operator is not detected correctly.

### ISSUE THREAD

**Issue by vishnudev-k** [opendatahub-io/odh-dashboard#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Using an OpenDataHub main version (eg. `v1.6.0`)

### Version

Openshift version - 4.9.59 RH Pipelines version - 1.7.3 ODH version - 1.6 (dashboard is main and kfDef is 1.7)

### Current Behavior

ODH dashboard is not detecting pipeline operators intermittently. 

I have tried triaging the issue by adding cluster role binding to my IAM user
 and momentarily got the pipeline enabled. (not sure if it's the fix or something else)

Later the dashboard started complaining about operator installation again. 

I am using IBM SSO for logging into the cluster. 
My username looks like this.
![image](https://github.com/opendatahub-io/odh-dashboard/assets/130466213/227de5b6-62e1-4089-815f-c29ee6670625)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/130466213/8764bba6-9ee0-4e82-9a8f-789f101b1523)

### Expected Behavior

ODH dashboard should detect pipelines operator without any config change.

**Comment by shalberd** [comment]
@andrewballantyne meaning the user of IBM SSO had to do this for Red Hat Openshift Pipelines Operator detection logic to work, though intermittently, the error message of Red Hat Openshift Pipelines not installed still appears.

```
kind: ClusterRoleBinding
apiVersion: [rbac.authorization.k8s.io/v1](http://rbac.authorization.k8s.io/v1)
metadata:
  name: cluster-reader-myusername
subjects:
  - kind: User
    apiGroup: [rbac.authorization.k8s.io](http://rbac.authorization.k8s.io/)
    name: "IAM#myusername@ibm.com"
roleRef:
  apiGroup: [rbac.authorization.k8s.io](http://rbac.authorization.k8s.io/)
  kind: ClusterRole
  name: cluster-reader
```
