### ISSUE TITLE
Container Size becomes unknown when an administrator updates the notebook sizes. 

### ISSUE THREAD

**Issue by erwangranger** [opendatahub-io/odh-dashboard#1513]
## Solution

Instead of saying `Unknown` with an error, display `Custom` instead when we cannot render a matching name.

---

So, today, after consulting with my co-administrator, we decided that the default Notebook Sizes were too generous and needed a haircut. 

The default values in the CR were: 

```yaml
  notebookSizes:
    - name: Small
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 8Gi
    - name: Medium
      resources:
        limits:
          cpu: '6'
          memory: 24Gi
        requests:
          cpu: '3'
          memory: 24Gi
    - name: Large
      resources:
        limits:
          cpu: '14'
          memory: 56Gi
        requests:
          cpu: '7'
          memory: 56Gi
    - name: X Large
      resources:
        limits:
          cpu: '30'
          memory: 120Gi
        requests:
          cpu: '15'
          memory: 120Gi

```

We changed that to the following: 

```yaml 
  notebookSizes:
    - name: Small
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: '1'
          memory: 2Gi
    - name: Medium-Small
      resources:
        limits:
          cpu: '4'
          memory: 8Gi
        requests:
          cpu: '2'
          memory: 4Gi
    - name: Medium
      resources:
        limits:
          cpu: '6'
          memory: 16Gi
        requests:
          cpu: '3'
          memory: 8Gi
    - name: Large
      resources:
        limits:
          cpu: '12'
          memory: 24Gi
        requests:
          cpu: '6'
          memory: 16Gi
    - name: X Large
      resources:
        limits:
          cpu: '32'
          memory: 64Gi
        requests:
          cpu: '16'
          memory: 32Gi
    - name: XX Large
      resources:
        limits:
          cpu: '64'
          memory: 512Gi
        requests:
          cpu: '32'
          memory: 256Gi
```

You will note how careful we were to keep the old names, only change their values, and add a couple new names. 
We figured that replacing the name "small" with "tiny" might cause issues, for example. 
Because previously-created workbenches with a size name that would no longer exist would result in ... bad things probably. 

I really wanted to confirm everything worked right away, but this settings takes a couple minutes to get applied, during which I got pinged by someone and spent 30 minutes talking to. 

When I needed to show that person something in the environment, I was met with this: 
![image](https://github.com/opendatahub-io/opendatahub-community/assets/32554862/b4b46928-1c31-4d0c-aa23-efabb9d6fea9)

Needless to say that was unexpected. The size is unknown, but the container will still spin up successfully. (presumably using the older version of small). (Actually, I checked... and yes, it still had the old size). 

I reverted my changes in the CR, to put back in the old values, and the project went back to "normal". 

This was not at all what I was expecting. 

Not only can I not update the size chosen by previously-created workbenches, but trying to so makes the interface go crazy. 

I think I need some guidance on how to achieve my goals here.
