### ISSUE TITLE
[Feature Request]: surfacing nested pipeline input parameters

### ISSUE THREAD

**Issue by yuanchi2807** [opendatahub-io/odh-dashboard#1519]
### Feature description

Components participating in a nested pipeline have their own custom configurations. For example, in one component, an English language model is loaded to process input data while in another component, it is configured to load a Spanish language model. 

A flat layout of all rolled up configuration parameters from all components can be challenging to interpret by pipeline users. It may be worth considering to improve user experience with grouping or hierarchical layouts.

**Comment by andrewballantyne** [comment]
@yuanchi2807 When you refer to nested Pipeline input parameter... how "nested" are we talking here? The way I understand how Tekton works is:
- (Top Level) Pipeline Parameters -- these are needed to start, or have a fallback
    - (Each) Task Parameters -- these can use the Pipeline Parameters, reference other values from other tasks

Here is the Tekton variable reference doc: https://tekton.dev/docs/pipelines/variables/

Could you provide more information?

**Comment by yuanchi2807** [comment]
@andrewballantyne Thanks for the link. On the DSP 'create run' configuration screen, how should I expect pipeline and task parameters be organized under sections?

**Comment by andrewballantyne** [comment]
@yuanchi2807 Creating a new Pipeline Run only has to answer the Pipeline Parameters. Not sure there is a good way to set internal task parameters. If you want some connectivity there, I imagine you write a Pipeline parameter and then your Task Parameter references the Pipeline Parameter for execution.

```
kind: PipelineRun
...
spec:
  params:
    - name: 'foo'
      description: 'Must be given before I can start'
  # this is probably nested under pipelineSpec or something
  tasks:
    - name: 'my-first-task'
      params:
        - name: 'bar'
          value: '$(params.foo)'
... 
```
Something like that... this was typed without testing, so refer to the Tekton docs to make sure you get the right syntax when you're testing it out.

I may have misunderstood your question from Slack, so apologizes for that. Let me know if this clears things up.
