### ISSUE TITLE
[Feature Request]: Add overlay for incubation deployment

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1614]
### Feature description

Add an overlay to deploy incubation with the right image easily.

That image should point to: `quay.io/opendatahub/odh-dashboard:nightly `

Ideally, we could get latest `incubation` image running this kfdef:

```yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: odh-dashboard
spec:
  applications:
    - kustomizeConfig:
        overlays:
          - incubation
        repoRef:
          name: manifests-incubation
          path: manifests
      name: odh-dashboard
  repos:
    - name: manifests-incubation
      uri: 'https://github.com/opendatahub-io/odh-dashboard/tarball/incubation'
```
