### ISSUE TITLE
[Feature Request]: Pull data science pipeline name and description from pipeline object

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#1682]
### Feature description

When defining a pipeline with kfp, you can set the name and the description of the pipeline as part of the pipeline code:

```python
@kfp.dsl.pipeline(
    name="Add Pipeline",
    description="A pipeline that adds numbers together",
)
def add_pipeline(a="1", b="7"):
    first_add_step = add_op(a, 4)
    second_add_step = add_op(first_add_step.output, b)
```

When converting the pipeline into a yaml object to upload to the dashboard, the yaml object that is generated creates the following annotation containing the name and description:

```yaml
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline that adds numbers
      together", "inputs": [{"default": "1", "name": "a", "optional": true}, {"default":
      "7", "name": "b", "optional": true}], "name": "Add Pipeline"}'
```

When uploading the pipeline to the dashboard, the dashboard should populate those fields from the yaml object:

![image](https://github.com/opendatahub-io/odh-dashboard/assets/1628206/cfa0d465-78bb-430a-89cb-8635904a9e97)
