### ISSUE TITLE
[Feature Request]: DSP input parameter groupings, rendering order

### ISSUE THREAD

**Issue by yuanchi2807** [opendatahub-io/odh-dashboard#1760]
### Feature description

Pipeline input parameters are rendered in alphabetical order today. 
User experience would improve to divide them into mandatory, optional fields to accomodate general and expert users. 
General users only need to fill in the mandatory section, where optional fields allow experts to further configure a pipeline.

**Comment by andrewballantyne** [comment]
@yuanchi2807 I'm fairly certain (looking at the code) we just render them in order they are in the params section... have you tried reordering your params to see if it reorders?

**Comment by yuanchi2807** [comment]
@andrewballantyne 
We put in 
```
    name: str = "LLM-pipeline",  # name of Ray cluster
    min_worker: int = 2,  # min number of workers
    max_worker: int = 2,  # max number of workers
    cluster_up_tmout: int = 5,  # minutes to wait for the Ray cluster achived min_worker number
    wait_cluster_ready_tmout: int = 0,  # seconds to wait for Ray cluster to become available
    wait_cluster_nodes_ready_tmout: int = 1,  # seconds to wait for cluster nodes to be ready
    ....
```
and the Pipeline input parameters section begins like this. 
<img width="265" alt="image" src="https://github.com/opendatahub-io/odh-dashboard/assets/84025022/31d30317-4108-42cd-939d-c80191fb2f77">

**Comment by andrewballantyne** [comment]
Ooooh, most interesting. Thanks for the additional information @yuanchi2807 

I am going to pull in some backend/notebook help to understand what is happening here. cc @harshad16 @HumairAK 

If things are all generated by Kubeflow & the SDK -- is there anyway for them to order the items? Because it seems the params might sort them on that side of things (either in Elyra or in some other fashion).

**Comment by roytman** [comment]
@andrewballantyne , you're right. It is done by the compiler, I see the input parameters according ABC in the yaml file.
e.g.
```yaml
  - name: execute-ray-jobs
      params:
      - name: checkpoint_path
        value: $(params.checkpoint_path)
      - name: cos_access_secret
        value: $(params.cos_access_secret)
      - name: http_retries
        value: $(params.http_retries)
      - name: init-notifier-output
        value: $(tasks.init-notifier.results.output)
      - name: input_path
        value: $(params.input_path)
      - name: output_path
        value: $(params.output_path)
      - name: script_name
        value: $(params.script_name)
      - name: start-ray-cluster-output
        value: $(tasks.start-ray-cluster.results.output)
      - name: switch
        value: $(params.switch)
      - name: wait_job_ready_retries
        value: $(params.wait_job_ready_retries)
      - name: wait_job_ready_tmout
        value: $(params.wait_job_ready_tmout)
      - name: wait_print_tmout
        value: $(params.wait_print_tmout)
        ```
