### ISSUE TITLE
Simplify deployment

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#20]
If you remove the `namespace`entries from `install/odh/base/kustomization.yaml`and `install/odh/base/role_binding.yaml`, the overlay called `default` is not needed for a standard ODH deployment and you can directly add:
```
- kustomizeConfig:
        repoRef:
          name: dashboard
          path: install/odh
      name: odh-dashboard
```
and
```
    - name: dashboard
      uri: 'https://github.com/opendatahub-io/odh-dashboard/tarball/master'
```
to the ODH instance YAML.
That's much easier imho than the `deploy.sh` script, plus it's the "standard" way to deploy an ODH component, which will make it easier to merge this as a standard component in a next release. `namespace` is not needed as the operator will take care of the deployment of all components in the right one.
I did not make a PR yet as I did not know what was the intent behind the deploy script, but I can easily as it's already implemented in my fork.

**Comment by cfchase** [comment]
@guimou the kustomize templates here in the project were meant to support a dev pipeline (e.g. if I wanted to deploy a customized image I built using the other build scripts) but will provide the basis for the operator deployment.  I expect I'll be adding those to templates similar to your suggestion to the odh-manifests project soon.

**Comment by cfchase** [comment]
@guimou I got rid of those namespace entries in the templates and now you can use the ODH operator to deploy the dashboard just like you suggested.  I left the `dev` overlay there for the purposes of allowing developers to [deploy custom images](https://github.com/opendatahub-io/odh-dashboard#deploying-your-image), but you should still be able to deploy the normal image.  You can just set the path to `install/odh/base`.  I added instructions to the [readme](https://github.com/opendatahub-io/odh-dashboard#open-data-hub-operator-deployment)

```yaml
    - kustomizeConfig:
        repoRef:
          name: odh-dashboard
          path: install/odh/base
      name: odh-dashboard
```
```yaml
    - name: odh-dashboard
      uri: 'https://github.com/opendatahub-io/odh-dashboard/tarball/master'
```

Let me know if you think this address the issue and I'll close it out.
