### ISSUE TITLE
[Feature Request]: Allow kubeadmin to act as Dashboard Admin

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#2006]
### Feature description

When initially setting up a cluster the first user that exists on that cluster is kubeadmin. Kubeadmin is a special user that is not assigned the cluster-admin role, but has similar (or greater) access than what is granted by cluster-admin.

Today the kubeadmin user is not permitted to access the admin resources of the dashboard.

kubeadmin should be a special condition that is checked for along with if the user is part of the cluster-admin role.

### Describe alternatives you've considered

Alternatively, you could do away with the check for belonging to a specific group/role and check for a specific capability of a user to determine if they should have admin access.  

For example, if they have create/edit access to the DSC.

Additionally you could have a specific role that grants permission to what we expect an admin of odh/rhods should be able to do and the UI could assign that role to any user/group that is updated in the user management section.  In the Dashboard to check if the user has permissions to be an admin, the UI would simply check to see if they have the correct action/verb access and the access could be gained through any form of RBAC access.

**Comment by andrewballantyne** [comment]
We don't want to support `kubeadmin` explicitly @strangiato. I tried to find docs to back up my conversations from a couple years ago with the OCP team... this is the best I have found on the doc side (I'll see about making a request to get better docs):
- [Optionally remove it](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html/installing_on_rhv/cli-logging-in-kubeadmin_installing-rhv-default#post-installation-tasks-2) this is the RH Virt docs for 4.5 🙁 
- [How to remove it](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/authentication_and_authorization/removing-kubeadmin#understanding-kubeadmin_removing-kubeadmin)
- [Added security note](https://docs.openshift.com/container-platform/4.13/authentication/remove-kubeadmin.html#removing-kubeadmin_removing-kubeadmin)
    > After you define an identity provider and create a new cluster-admin user, you can remove the kubeadmin to improve cluster security.

I asked the OCP team and they inform me of these shortcomings:
- kubeadmin can never have their password changed, if that gets compromised, you’re out of luck
- if multiple people use the login, there is no way to lock out some access
- if the password is "lost", it's annoying to recover (it's in the [installation log](https://access.redhat.com/solutions/6856471))

`kubeadmin` is convenient for our testing clusters, but it's not a real world need as `kubeadmin` is very problematic for the reasons listed above.

If you want to test with kubeadmin, you can always grant them `cluster-admin`:
```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: add-kubeadmin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'kube:admin'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```
or add them to your ODH Admins group noted in your OdhDashboardConfig (or in the Admin UI)
```yaml
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: odh-dashboard-admins # whatever your admin group is called
users:
  - 'b64:kube:admin'
  # other admins you want
```
