### ISSUE TITLE
[Story]: Edge model table view

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#2064]
### Goal

Create a page to showcase all added models

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/2061

### Itemized goals

- Page should include:
   - Table
      - Columns: name, location (s3 or git), framework, lifecycle
      - lifecycle table data should be a progress stepper
         - TBD where to get progress is base don the final pipeline, but generally we can get status of each step like this
             - a pipeline run yaml will have the structure. You can use the conditions to check the status of each task. then pipeline will (TBD) be a linear flow so the stepper should fit into this use case easily
                ``` yaml
                spec:
                   pipelineSpec:
                      tasks:
                         - name: task-name
                           status:
                               conditions: 
                                  - 
                ```
             
   - Add model button

### Aspects continued elsewhere

- https://github.com/opendatahub-io/odh-dashboard/issues/2062

### Mocks

TBD
