### ISSUE TITLE
[Story]: Add annotations for kserve InferenceService

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2079]
### Goal

Add missing annotations to InferenceServices for kserve

### Dependency issue

No dependencies

### Itemized goals

Add the following annotations:

```yaml
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
```

### Mocks

No mocks
