### ISSUE TITLE
[Bug]: Cleanup caikit ootb runtime

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

main

### Current Behavior

A little bit of a cleanup still needed for the [caikit-ootb.yaml](https://github.com/opendatahub-io/odh-dashboard/blob/8344e6d3761e3def23c2357f01dd4942870cf452/manifests/modelserving/caikit-ootb.yaml).

### Expected Behavior

Add an additional env var in [caikit-ootb.yaml](https://github.com/opendatahub-io/odh-dashboard/blob/8344e6d3761e3def23c2357f01dd4942870cf452/manifests/modelserving/caikit-ootb.yaml#L42C1-L44C31)

Expected output:
```
        env:
          - name: RUNTIME_LOCAL_MODELS_DIR
            value: /mnt/models
          - name: RUNTIME_GRPC_SERVER_THREAD_POOL_SIZE
            value: 64
```

---

Remove ports name field in [caikit-ootb.yaml](https://github.com/opendatahub-io/odh-dashboard/blob/8344e6d3761e3def23c2357f01dd4942870cf452/manifests/modelserving/caikit-ootb.yaml#L47) as this will cause some issues with KServe.

### Steps To Reproduce

Go to Settings => Serving Runtimes & view the YAML for the ootb caikit runtime
