### ISSUE TITLE
[Bug]: Service Mesh Code for reading the flag in the Jupyter Tile is wrong

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

incubation

### Current Behavior

The [code](https://github.com/opendatahub-io/odh-dashboard/blob/44496c198dc3dd31749fc540dcdab596044d8ad1/backend/src/utils/notebookUtils.ts#L280-L282) flips the flag too much -- and is now inverted.

### Expected Behavior

Let the utility handle the understanding of the flag and not invert the result.

### Steps To Reproduce

Make sure the feature flag is disabled (value 'true').

1. Create a Jupyter tile Notebook
2. View the Notebook resource in OpenShift Console for no OAuth Container

**Comment by cam-garrison** [comment]
After investigation yesterday afternoon and this morning, I'm finding that the issue only comes up when there's a pre-existing notebook. 

So, with no notebook and `disableServiceMesh: false` -> create notebook:
```
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "false"
    opendatahub.io/service-mesh: "true"
  labels:
    sidecar.istio.io/inject: "true"
```
which is correct/expected behavior. But if we stop this notebook and restart it through the jupyter tile:
```
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "false"
    opendatahub.io/service-mesh: "false"
  generation: 2
  labels:
    sidecar.istio.io/inject: "false"
```
and similarly for a fresh notebook when `disableServiceMesh: true` -> 
```
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    opendatahub.io/service-mesh: "false"
  generation: 1
  labels:
    sidecar.istio.io/inject: "false"
```
which is expected/correct, and the oauth-proxy container is injected. 
Now, restarting the notebook through the jupyter tile:
```
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "false"
    opendatahub.io/service-mesh: "true"
  generation: 2
  labels:
    sidecar.istio.io/inject: "true"
```

So, it's a bit odd as in the case when using `disableServiceMesh: true` we flip all three "flags" (for lack of better word) on notebook restart, but in the case when `disableServiceMesh: false`, we flip only two "flags" on restart.
