### ISSUE TITLE
[Bug]: Fail to deploy a model using Caikit ServingRuntime on GPU node

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#2211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `OpenShift AI 2.4`)

### Version

2.5 pre-RC

### Current Behavior

As soon as I click on "deploy" button after filling out the model serving form, the models reports error: 
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/866cc1bc-386f-42ba-8ae1-342a56d05166)

The inference service object reports `InvalidSpec` error:

```
status:
  modelStatus:
    lastFailureInfo:
      message: Waiting for runtime to become available
      reason: RuntimeNotRecognized
    states:
      activeModelState: ''
      targetModelState: FailedToLoad
    transitionStatus: InvalidSpec
```

The model pod is not created.

Could it be related to https://github.com/opendatahub-io/odh-dashboard/issues/2193? 

### Expected Behavior

Model gets deployed successfully on GPU node

### Steps To Reproduce

1. enable kserve in DSC
2. enable single-model platform Dashboard settings
3. create a DS project
4. click on "Deploy model" button in the DS project
5. fill out the form with correct information
6. click on "Deploy" button
7. check what happens

### Anything else

Caikit runtime definition copied from https://github.com/red-hat-data-services/odh-manifests/pull/530/files#diff-ff2f3f0c41c5aef01e48e3a2fe8361b2c7d8401cc6086d5bcc345c94dc5ab494R1 (I replaced the image fields with the right image URLs)
