### ISSUE TITLE
Improve Issue Templates

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#250]
**Describe the solution you'd like**
We want to use Github Issues as a tracker for new requests. We want to improve the template we are currently using to fit our new requirements.

**Comment by lucferbux** [comment]
@DaoDaoNoCode @dlabaj @maroroman @samuelvl 
This is the new yaml format for the requests, I've created a [mock project here](https://github.com/lucferbux/issue_template_mock/issues/new/choose) just to check how it works.
These are the new templates, let me know what you think:

**Bug report**

```yaml
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - lucferbux
  - DaoDaoNoCode
  - dlabaj
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please, fill this form to help us improve the project.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if any)
      description: Any manual steps that allow you to resolve the issue
      placeholder: Tell us the steps you followed to resolve the issue!
    validations:
      required: false
  - type: dropdown
    id: openshift-version
    attributes:
      label: Openshift Version
      description: What version of Openshift are you running?
      options:
        - Baremetal
        - OpenStack
        - RHV
        - AWS
        - OKD
        - CodeReady Containers
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: textarea
    id: opendatahub-version
    attributes:
      label: Open Data Hub Version
      description: Please attach relevant kfdef manifest if applicable
      render: yaml
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
```

**feature request**
```yaml
name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]
assignees:
  - lucferbux
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please, fill this form to help us improve the project.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description 
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: describe-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Tell us about alternatives you've considered...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
```
