### ISSUE TITLE
[KFNBC]: UI - Use environment variables of the notebooks in a different way 

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#282]
### Feature description

When we create the environment variable files (secrets, configmaps), we don't need to refer to them in the NotebookControllerState, instead, we should set them as the env reference in the container of the notebook when we create them.
here is an example:
```
- name: ODH_EXAMPLE_CM
  valueFrom:
    configMapKeyRef:
      key: ODH_EXAMPLE_CM
      name: jupyterhub-singleuser-profile-htpasswd-2dcluster-2dadmin-2duser-envs
- name: ODH_EXAMPLE_SECRET
  valueFrom:
    secretKeyRef:
      key: ODH_EXAMPLE_SECRET
      name: jupyterhub-singleuser-profile-htpasswd-2dcluster-2dadmin-2duser-envs
```
