### ISSUE TITLE
[KFNBC]: Backend will create RBAC rule to enable authorization for normal users for KFNBC

### ISSUE THREAD

**Issue by maroroman** [opendatahub-io/odh-dashboard#290]
### Bug description

As per known issues in: #267 

- Backend will create the following RBAC rule to enable authorization for normal users:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${NOTEBOOK_NAME}-notebook-view
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - notebooks
    resourceNames:
      - ${NOTEBOOK_NAME}
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${NOTEBOOK_NAME}-notebook-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${NOTEBOOK_NAME}-notebook-view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${USER}
```
