### ISSUE TITLE
[KFNBC]: After server is ready user should be automatically redirected

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#305]
### Feature description

After spawning a server, the user should be redirected to it rather than left in the control panel page

**Comment by samuelvl** [comment]
@DaoDaoNoCode Does javascript allow this behaviour?

**Comment by DaoDaoNoCode** [comment]
@samuelvl This is what I am talking about, the browser doesn't allow you to open a new tab, but it allows you to replace the URL of the current tab, so that's why we need an access point in the Jupyter Notebook to navigate us back to the dashboard. Once we have that, we could implement the behavior mentioned in this issue.

**Comment by DaoDaoNoCode** [comment]
@samuelvl I found an issue when implementing this. Since we change the `ServerApp.base_url` here, when we log out of the notebook, then we log in, we will always go to the `notebook_url` without `base_url`, which means we will get a 404 error when we log out and log in again.
Do you have any solution?

**Comment by samuelvl** [comment]
@DaoDaoNoCode Nice catch, we can use the `--logout-url` flag in the oauth-proxy. I will open a PR to support a new annotation to set this flag:

```
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/oauth-logout-url: https://${notebook_url}/notebook/${namespace}/${notebook}
```
