### ISSUE TITLE
[Bug]: RHOAIENG-16192 deleting a workbench also deletes envFrom configmaps and secrets not created by dashboard and not unique by name AND workbench

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#3521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

main, v2.29.1-odh

### Current Behavior

Deleting a notebook / workbench currently has logic in it to also delete associated configmaps and secrets listed in the notebook container's envFrom section.
That deletion occurs by name and assumes that each secret and configmap is only associated to that one workbench / notebook and has a unique name in the namespace per workbench, either configmap or secret having been generated by odh dashboard.

This logic is a problem when we have configmaps and secrets as envFrom basis that have not been generated by dashboard.
Because those configmaps and secrets are often times created by CICD processes, not by dashboard, and linked up currently to the container envFrom section envFrom list via other processes (cronjob patch, ArgoCD).

In preparing for later being able to select existing secrets and configmaps from a [dropdown list in the GUI env section as well](https://github.com/opendatahub-io/odh-dashboard/issues/1380), I tagged the configmap and secret with label
`opendatahub.io/dashboard: 'true'` but **not** with label `opendatahub.io/managed: 'true'`.
In essence, dashboard-related: yes    .... managed by odh or dashboard: no

Preparation steps are described in "Steps to Reproduce".
After those steps, we can check this test config in the dashboard GUI as well. The refs show up in the form of the two new env variables in both workbenches jupyter and jupyter2:
![20241126 Workbench Edit GUI shows new env from CICD ConfigMap](https://github.com/user-attachments/assets/e37362c4-5a9c-4658-b991-8cd0eefb3fa2)
![20241126 Workbench Edit GUI shows new env from CICD Secret](https://github.com/user-attachments/assets/b745deea-7be6-4344-99d7-5a32310cd3c9)

**If you now delete one of the two workbenches**, it does not really matter, via Dashboard GUI .... the unique name per namespace; not workbench, and not managed by ODH, secret and configmap will no longer be there.

Which in the other remaining workbench will lead to problems, obviously, because it references the configmap and secret ...

### Expected Behavior

probable root cause:

configmaps and secrets to delete are deleted by name only as they appear in envFrom list, when workbench is deleted:

https://github.com/opendatahub-io/odh-dashboard/blob/v2.29.1-odh-release/frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx#L35

Expected:

- immediate fix: When deleting associated secrets and configmaps, dashboard should only delete secrets and configmaps that, in addition to being listed in the envFrom section, also have the label `opendatahub.io/managed: 'true'`
- possible bonus: **do not assume that the names of configmaps and secrets listed in envFrom are unique by workbench**, even though that is currently the case when generated/created via dashboard GUI env Section Configmap and Secret. In Openshift and K8S, objects are named unique by namespace, not by other objects they are referenced by. Imagine in a possible later scenario, e.g. odh notebook controller or odh operator could apply secrets and configmaps with envs used across workbenches and namespaces with names of configmap and secret that are unique by namespace, not by workbench and link them up by name to each workbench in a namespace, optionally. With label `opendatahub.io/dashboard: 'true'` so they can in a future version of dashboard be show in a dropdown list in the GUI as well, should they not already be attached ...
- What our ArgoCD / Cronjob patch process does currently, same applies to a future GUI solution, selecting from existing configmaps and secrets in namespace as a source of env Variables ... that, too, will mean the same-name configmap and secret can be attached to multiple workbenches / notebooks envFrom.

### Steps To Reproduce

Preparation steps:
- Use a certain data science project / namespace
- Have two workbenches created in data science project via Dashboard GUI, let's say newjupyter and newjupyter2
- Have sample configmap and secret as basis for CICD-level env vars created manually in that namespace / data science project:

```
kind: Secret
apiVersion: v1
metadata:
  name: sample-cicdsecret-envs-multiple-workbenches
  labels:
    app: opendatahub
    app.kubernetes.io/name: opendatahub
    mycorporation/cicdorigin: argocd
    opendatahub.io/dashboard: 'true'
data:
  USER_PW: bXlzYW1wbGVwYXNzd29yZDM0
type: Opaque
```

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: sample-cicd-configmap-envs-multiple-workbenches
  labels:
    app: opendatahub
    app.kubernetes.io/name: opendatahub
    mycorporation/cicdorigin: argocd
    opendatahub.io/dashboard: 'true'
data:
  STAGE: tst
```
![20241126 CICD envVar Secret in Namespace with no odh managed label](https://github.com/user-attachments/assets/4f1c685d-aaae-4500-bf89-8b8a48813c98)
![20241126 CICD envVar ConfigMap in Namespace with no odh managed label](https://github.com/user-attachments/assets/a8be3955-aa4d-4496-8c67-c9b8bd6912c8)

- Hook up the secret and configmap to the two workbenches' newjupyter and newjupyter2 by either going into each notebook container's envFrom section or by patching with oc command, whatever is most intuitive to you in the data science project namespace ...

```
oc get notebook newjupyter -o json | jq '.spec.template.spec.containers[0].envFrom += [{"configMapRef" {"name":"sample-cicd-configmap-envs-multiple-workbenches"}}]' | oc apply -f -;

oc get notebook newjupyter2 -o json | jq '.spec.template.spec.containers[0].envFrom += [{"configMapRef" {"name":"sample-cicd-configmap-envs-multiple-workbenches"}}]' | oc apply -f -;

oc get notebook newjupyter -o json | jq '.spec.template.spec.containers[0].envFrom += [{"secretRef":{"name":"sample-cicdsecret-envs-multiple-workbenches"}}]' | oc apply -f -;

oc get notebook newjupyter2 -o json | jq '.spec.template.spec.containers[0].envFrom += [{"secretRef":{"name":"sample-cicdsecret-envs-multiple-workbenches"}}]' | oc apply -f -;
```

Result in the two notebooks needs to be in the envFrom section of the notebook container, the first container:

```
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: newjupyter
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/ca-trust/extracted/pem
              name: trusted-ca
              readOnly: true
          envFrom:
            - configMapRef:
                name: sample-cicd-configmap-envs-multiple-workbenches
            - secretRef:
                name: sample-cicdsecret-envs-multiple-workbenches
```

### Workaround (if any)

no workaround currently, as deletion happens in code
