### ISSUE TITLE
[KFNBC]: Do not delete notebook CR when starting/stopping a notebook

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/odh-dashboard#387]
### Feature description

In order to preserve a user's previous settings so they can quickly start/stop a notebook, we should simply stop and start the notebook.  In this case, when restarting a notebook, the spawner should load all the notebook's existing settings.

**Comment by andrewballantyne** [comment]
This will be in conjunction with making the ODH Dashboard Config more "Config" and less "What we need for the Dashboard". The growing "Config" side of the coin can be found here: https://github.com/opendatahub-io/odh-dashboard/pull/385

**Comment by samuelvl** [comment]
The controller already supports this by adding an annotation to the notebook CR (it's used by the culler to stop notebooks):

``` 
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    kubeflow-resource-stopped: "$(date)"
```

See https://github.com/opendatahub-io/kubeflow/blob/master/components/notebook-controller/pkg/culler/culler.go#L40
