### ISSUE TITLE
[Bug]: Empty notebookControllerState entry added

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you start with a new dashboard config CR, you will always find the CR updated with an empty entries like
```
status:
  notebookControllerState:
    - lastSelectedImage: ''
      lastSelectedSize: ''
      user: ''
```

### Expected Behavior

There should be only the entry with the username updated. The empty entry shouldn't be patched to the dashboard config.

### Steps To Reproduce

1. Remove `status` from dashboard config CR.
2. Go to the notebook controller
3. Go back to the CR, you will see a new entry under the CR, which is the bug empty one.

### Workaround (if any)

This doesn't affect the functionality though, the admin panel will do the clean-up before mapping the users in the admin panel servers table.
