### ISSUE TITLE
[Conversation]: Ability to have a default notebook size

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#431]
### Feature description

As per https://issues.redhat.com/browse/RHODS-3625, we are adding the ability to configure **NB container sizes**, one of the features would be the ability to select a default notebook size (see mockup bellow).

<img width="1223" alt="Screenshot 2022-08-22 at 15 59 31" src="https://user-images.githubusercontent.com/16117276/185939353-d1d5718e-0f1c-4d0c-9f36-165fb4caf72d.png">

We need to figure out how to add this logic to the dashboard and how the spawner will behave with the default size.

**Comment by andrewballantyne** [comment]
## Our current setup.

We have one `OdhDashbardConfig` -- in the Dashboard namespace. It has a simple array of items:
```
spec:
  ...
  notebookSizes:
    - name: Small
      resources:
        limits:
          cpu: '2'
          memory: 2Gi
        requests:
          cpu: '1'
          memory: 1Gi
    - name: Medium
      resources:
        limits:
          cpu: '4'
          memory: 4Gi
        requests:
          cpu: '2'
          memory: 2Gi
    ...etc
```

We need to flag one of these as a default -- we did away with the JH's design of a custom standalone default in https://github.com/opendatahub-io/odh-dashboard/issues/345 but we still need to configure the existing ones as a default.

Currently out logic ([frontend code](https://github.com/opendatahub-io/odh-dashboard/blob/e1bb39fbb385d3b701704c956280676e7ffa4d50/frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts)) determines a smart default for the user. We have https://github.com/opendatahub-io/odh-dashboard/issues/303 to cover a local on-going selection which likely will update the frontend code's hook.

For this effort, we need some way for the admin to configure the default for users without one. And to markup the dropdown of the Notebook Size to show the user which is the default that is suggested to use.

Discussed briefly with Kyle, we'll go with `<Size Name> (Default)` as the dropdown label (eg `Small (Default)`). This is configured on the admin view that Lucas is showing in the description.

## The suggestion

I think the best solution is to do the following:

- Move `notebookSizes` into `notebookController`
- Add `defaultSize` as a property -- this is a free-form text field, which will match on the `notebookSizes[].name` of one of the sizes
    - If the UI loads and this is not matchable:
        - The spawner page will default to the first one (if no user preference is set) and we omit (`Default`) from the dropdown items
        - The admin UI simply just shows nothing as a default. Could come with a top-page warning of the issue and encourage selecting a default -- that's up to UX

This will need a migration script to move existing items around in the CR/CRD.

---

If modifying the CRD is not desired, we can go with the same `defaultSize` in the `notebookController` section of the CRD -- this still works out.

I don't think adding a `default: true` property to any of the `notebookSizes[]` items is a good idea, because it can lead to a config that looks rough and doesn't align with the frontend (as we will just take the first one -- only 1 can be the default).
