### ISSUE TITLE
[DSG]: Fix On-Cluster K8s Pass Through

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#479]
During testing of my PR #279 there was an issue on-cluster. The user would get 403 forbidden errors because the oauth x-forwarded token would not have enough permissions to grant the needed access to the user's permissions.

When you're using it locally, it works fine because you are logged in as your user and skipping past the oauth containers.

Samu explained an approach [here](https://github.com/opendatahub-io/odh-dashboard/pull/279#issuecomment-1235371892). This is going to be a manifest update / cluster setup situation. Should improve the x-forwarded token's underlying permissions.

THIS WILL BLOCK DSG from `main` if it is not resolved.

**Comment by samuelvl** [comment]
The dashboard SA does not have permissions to use `user:full` scope. A dedicated OAuthClient has to be created for this:

```yaml
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: odh-dashboard
grantMethod: auto
redirectURIs:
- ${OAUTH_CLIENT_URL}
secret: ${OAUTH_CLIENT_SECRET}
``` 

The opendatahub-operator should be extended to create this object, replacing OAUTH_CLIENT_URL and OAUTH_CLIENT_SECRET variables. The new secretGenerator controller can be used to do this, by using a new annotation:

```
apiVersion: v1
kind: Secret
metadata:
  name: example
  annotations:
    secret-generator.opendatahub.io/oauth-client-route: "odh-dashboard"
type: Opaque
```

The operator will create an `OAuthClient` with the secret and route url values. After this, the dashboard oauth proxy flags have to updated to use:

```
--client-id=odh-dashboard
--client-secret-file=<mount the generated secret file>
--scope=user:full
```
