### ISSUE TITLE
[Bug]: Secure routes cause Liveness and Readiness probes to timeout the dashboard pod

### ISSUE THREAD

**Issue by maroroman** [opendatahub-io/odh-dashboard#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Liveness/Readiness probes check the api/config endpoint to check whether the dashboard pod is ready. However the new secure routes require a username which the probes do not have, resulting in a timeout and a crash.

### Expected Behavior

Liveness/Readiness probes correctly access the dashboard or use a different method.

### Steps To Reproduce

1. Deploy latest dashboard implementation with a deployment containing probes.
2. Verify that the dashboard is crashlooping.
3. Remove probes
4. Verify that the dashboard is working.

### Workaround (if any)

Delete readiness/liveness probes.

### Open Data Hub Version

```yml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: "false"
  name: odh-dashboard-kfnbc-test
  namespace: opendatahub
spec:
  applications:
  - kustomizeConfig:
    # We just need this for creating the ODH default notebook images that are provided by ODH JupyterHub
    #TODO: Replace with the new ODH default notebook images as part of ODH Core
      overlays:
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-notebook-controller
    name: odh-notebook-controller
  - kustomizeConfig:
      overlays:
      - authentication
      # Uncomment the odhdashboard overlay below to have the operator deploy the configs
      # This should be removed from the deployed kfdef immediately after the operator deploys the configs
      # This will prevent the operator from reconciling the configs when they have been modified externally
      #- odhdashboardconfig
      repoRef:
        name: manifests-dashboard  # Use the odh-dashboard repo as the source for this kustomize manifest
        path: manifests
    name: odh-dashboard
  repos:
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/master
  - name: manifests-dashboard  # Use the manifests from the odh-dashboard repo
    uri: https://github.com/opendatahub-io/odh-dashboard/tarball/main
```

### Relevant log output

```shell
{"level":50,"time":1663063141964,"pid":77,"hostname":"odh-dashboard-77f9dd54b-kpc4l","msg":"Error retrieving username: Error getting Oauth Info for user, missing x-forwarded-access-token header
```
