### ISSUE TITLE
[Bug]: OdhApplication.spec.betaText has non-generic default text

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/odh-dashboard#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If an OdhApplication CR is applied with spec.beta=true but no spec.betaText, there is a information banner displayed on the side panel after clicking the respective tile in "Explore" tab that states "This application is available for early access prior to official release. It won’t appear in the Enabled view, but you can access it by [signing up for beta access.](https://www.starburst.io/platform/starburst-galaxy/).".  

This text seems to be specific to a beta release of Starburst Galaxy, and should be updated to something more generic.

### Expected Behavior

When spec.beta is set to true but spec.betaText is not set, the beta information banner text  should be updated to something more generic such as simply "This application is available for early access prior to official release."

### Steps To Reproduce

1. Apply an OdhApplication CR[1] with beta: true and no betaText defined
2. Go to ODH Dashboard UI
3. Click on **Explore** menu item
4. Click on the OdhApplication Tile just created
5. Verify the beta information banner (text in blue background)

[1] Example OdhApplication CR:
```yaml
apiVersion: dashboard.opendatahub.io/v1
kind: OdhApplication
metadata:
  name: test-app-tile
spec:
  beta: true
  category: Test
  description: Test App
  displayName: Test App
  docsLink: https://www.example.com
  img: foo
  getStartedLink: https://www.examplecom
  getStartedMarkDown: "foo"
  provider: Test
  support: Test
```

### Workaround (if any)

This can be worked around by simply setting the betaText field for any new OdhApplication CR that also uses the beta boolean field.

### Openshift Version

4.10

### What browsers are you seeing the problem on?

Firefox

### Open Data Hub Version

```yml
1.13
```

### Relevant log output

```shell
N/A
```
