### ISSUE TITLE
[Bug]: OdhApplication CR: spec.betaText not shown if spec.betaTitle not set

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/odh-dashboard#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If, while creating an OdhApplication CR, the `spec.beta` is set to true and `spec.betaText` is specified, but `spec.betaTitle` is not, the default betaText is displayed in the info banner rather than the text provided in the CR

### Expected Behavior

betaText, if set, should be displayed instead of default text regardless if betaTitle is set or not

### Steps To Reproduce

1. Apply an OdhApplication CR[1] with beta: true, betaText defined, and no betaTitle
2. Go to ODH Dashboard UI
3. Click on Explore menu item
4. Click on the OdhApplication Tile just created
5. Verify the beta information banner (text in blue background)

[1] Example OdhApplication CR:

```yaml
apiVersion: dashboard.opendatahub.io/v1
kind: OdhApplication
metadata:
  name: test-app-tile
spec:
  beta: true
  betaText: this should be displayed
  category: Test
  description: Test App
  displayName: Test App
  docsLink: https://www.example.com
  img: foo
  getStartedLink: https://www.examplecom
  getStartedMarkDown: "foo"
  provider: Test
  support: Test
```

### Workaround (if any)

Set betaTitle to title and betaText will then use the provided value

### Openshift Version

4.10

### What browsers are you seeing the problem on?

Firefox

### Open Data Hub Version

```yml
1.13
```

### Relevant log output

```shell
N/A
```
