### ISSUE TITLE
[Bug]: OdhApplication CR: Having a kfdefApplication list defined removes feature flag enable button

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/odh-dashboard#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Feature "Enable" button is not displayed in a Dashboard Tile if an OdhApplication has a non-empty list of kfdefApplications defined.

### Expected Behavior

The Enable/Disable functionality of the OdhApplication tile should still work if a kfdefApplication is defined.

### Steps To Reproduce

1. Install ODH
2. Apply a kfdef with at least 1 application (named 'foo')
3. Create an OdhApplication using the provided yaml
4. Go to ODH Dashboard > Explore and click on the Test App Tile
5. Verify that an enable button is missing on the right-hand side panel

[1] Example OdhApplication YAML:
```yaml
apiVersion: dashboard.opendatahub.io/v1
kind: OdhApplication
metadata:
  name: test-app-tile
spec:
  category: Test
  description: Test App
  displayName: Test App
  docsLink: https://www.example.com
  img: foo
  getStartedLink: https://www.example.com
  getStartedMarkDown: "foo"
  provider: Test
  support: Test
  kfdefApplication: ['foo']
  enable:
    title: test
    actionLabel: Enable
    description: Test
    validationConfigMap: test-tile-kfdefapplication-validator-result
    
```

### Workaround (if any)

Set the kfdefApplications value to [].  This removes the kfdef-check functionality, however.

### Openshift Version

4.10

### What browsers are you seeing the problem on?

Firefox

### Open Data Hub Version

```yml
1.13
```

### Relevant log output

```shell
N/A
```
