### ISSUE TITLE
[Bug]: odh-dashboard authentication overlay service error in ODH operator 1.4.0 log, OCP 4.10.36

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Manifests version / tag 1.4.0

OCP Cluster Version 4.10.36

KfDef:

```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      overlays:
      - authentication
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ceph/object-storage/scc
    name: ceph-nano-scc
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ceph/object-storage/nano
    name: ceph-nano
  - kustomizeConfig:
      overlays:
      - trusted-ca-bundle-path
      parameters:
        - name: trusted-ca-bundle-path
          value: "/opt/app-root/etc/jupyter/custom/cacerts/trustedcas.pem"
        - name: s3_endpoint_url
          value: "http://ceph-nano-0"
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  - kustomizeConfig:
      overlays:
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  repos:
  - name: manifests
    uri: https://repo.internal.ch/artifactory/datascience_internal/opendatahub-io-odh-manifests-v1.4-0.tar.gz
  version: master
```

Application deployment in namespace does not proceed correctly, stuck at stage odh-dashboard. Error message:
```
...
rolebinding.rbac.authorization.k8s.io/odh-dashboard serverside-applied
deployment.apps/odh-dashboard serverside-applied
time="2022-11-11T13:27:22Z" level=info msg="Watch a change for Kubeflow resource: odh-dashboard.odhsven."
time="2022-11-11T13:27:22Z" level=info msg="Watch a change for Kubeflow resource: odh-dashboard.odhsven."
route.route.openshift.io/odh-dashboard serverside-applied
time="2022-11-11T13:27:22Z" level=warning msg="Encountered error applying application odh-dashboard:  (kubeflow.error): Code 500 with message: Apply.Run : Service \"odh-dashboard\" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]"
time="2022-11-11T13:27:22Z" level=warning msg="Will retry in 5 seconds."
secret/dashboard-oauth-config serverside-applied
serviceaccount/odh-dashboard serverside-applied
...
```

Currently, base service is

https://github.com/opendatahub-io/odh-manifests/blob/master/odh-dashboard/base/service.yaml

overlay is

https://github.com/opendatahub-io/odh-manifests/blob/master/odh-dashboard/overlays/authentication/service.yaml

unclear why the error message spec.ports[1].name missing is appearing, there is no port 1, but probably a follow-up error.

ODH Deployment is stuck because of this. No other software, like in my case jupyter, is installed.

### Expected Behavior

service odh-dashboard is created correctly

probably, a name needs to be added in the form of an add-operation to the port in the authentication overlay.

rest of the KfDef components are created correctly

could be a related error to the bug in 4.10 that is only fixed in OCP 4.11:

https://bugzilla.redhat.com/show_bug.cgi?id=2077943

In any case, adding a port name to the one service port is no big deal so that it works with 4.10.

### Open Data Hub Version

```yml
1.4.0
```
