### ISSUE TITLE
[Bug]: ceph-nano ODH 1.4.0 on Openshift OCP 4.10.36 manifests tag 1.4.0

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

KfDef:

```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      overlays:
      - authentication
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ceph/object-storage/scc
    name: ceph-nano-scc
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ceph/object-storage/nano
    name: ceph-nano
  - kustomizeConfig:
      overlays:
      - trusted-ca-bundle-path
      parameters:
        - name: trusted-ca-bundle-path
          value: "/opt/app-root/etc/jupyter/custom/cacerts/trustedcas.pem"
        - name: s3_endpoint_url
          value: "http://ceph-nano-0"
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  - kustomizeConfig:
      overlays:
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  repos:
  - name: manifests
    uri: https://repo.internalserver.ch/artifactory/datascience_internal/opendatahub-io-odh-manifests-v1.4-0.tar.gz
  version: master
```

opendatahub-operator log when using ceph. Seems to be an issue with the ceph-nano StatefulSet.
https://github.com/opendatahub-io/odh-manifests/blob/master/ceph/object-storage/nano/base/statefulset.yaml

```
serviceaccount/ceph-nano serverside-applied
role.rbac.authorization.k8s.io/ceph-nano-secrets serverside-applied
rolebinding.rbac.authorization.k8s.io/ceph-nano-secrets serverside-applied
service/ceph-nano serverside-applied
service/ceph-nano-0 serverside-applied
time="2022-11-11T15:53:15Z" level=warning msg="Encountered error applying application ceph-nano:  (kubeflow.error): Code 500 with message: Apply.Run : failed to create typed patch object (odhsven/ceph-nano; apps/v1, Kind=StatefulSet): .spec.template.spec.containers[name=\"ceph-nano\"].protocol: field not declared in schema"
```

### Expected Behavior

Ceph-nano is applied correctly and fully.

### Open Data Hub Version

```yml
1.4.0
```
