### ISSUE TITLE
Reconsider usage of dockerImageRepository from imagestream status field in image field of assembled Notebooks

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#813]
### Feature description

https://github.com/opendatahub-io/odh-dashboard/search?q=dockerImageRepository

Currently, across the board in both frontend (Jupyter, same namespace for Notebooks as namespace of ODH Instance) and backend (different namespaces posssible), the imageUrl referenced in Notebook image: field is constructed from Imagestream status ' dockerImageRepository (varialbe imageUrl in the code).

That entry is empty and non-existent when there is no openshift-internal docker registry / dockerImageRepository used.

```
     from:
        kind: DockerImage
        name: 'quay.io/thoth-station/s2i-generic-data-science-notebook:v0.0.5'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
status:
  dockerImageRepository: ''
  tags:
    - tag: v0.0.5
      items:
        - created: '2022-11-21T13:14:31Z'
          dockerImageReference: >-
            quay.io/thoth-station/s2i-generic-data-science-notebook@sha256:3f619c61501218f03d39d97541336dee024f446e64f3a47e2bc7e62cddeb2e58
          image: >-
            sha256:3f619c61501218f03d39d97541336dee024f446e64f3a47e2bc7e62cddeb2e58
          generation: 2
```

**Consider instead to use imagestream name and tag for referencing images.** 

For cases where Notebook CRD is in a different namespaces than the rest of the software (odh notebook controller, odh dashboard, you need to allow the service account to access an imagestream in a different namespace (system:image-puller).

That seems to be the case, however, already, 
https://github.com/opendatahub-io/odh-dashboard/blob/c683fef35416e65d974711476e6b0396eceae673/frontend/src/utilities/notebookControllerUtils.ts#L159

which makes the case for referencing imagestream name and tag  in a Notebok container even more valid.

publicDockerImageRepository is not a solution, either, because that is dependent on the internal registry, too, plus it being exposed externally:

> PublicDockerImageRepository represents the public location from where the image can be pulled outside the cluster. This field may be empty if the administrator has not exposed the integrated registry externally.

Already, in the types, those fields are not mandatory, optional, which is great.

### Anything else?

Absolute blocker on all environments that use no openshift-internal docker registry. Especially critical because Jupyterhub is no longer maintained and customers are encouraged to switch to Dashboard plus Notebook controller / Notebook CRDs.
