### ISSUE TITLE
[Model Serving]: Dynamic spec of ServingRuntime 

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#814]
### Feature description

ServingRuntime creations is based in a [default template](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/api/network/servingRuntimes.ts#L23) with a harcoded image, we want to support:

1. Dynamic creation based on CRDs
2. Dynamic image fetching for the ServingRuntime container

## Dynamic creation based on CRDs
We wanna figure out a way to just include some options for modifying the actual spec of the object

## Dynamic image fetching for the ServingRuntime container
We might wanna retrieve this image dynamically from the operator.

Both of them need further investigation for the implementation.

**Comment by lucferbux** [comment]
For the image tagging, @anishasthana noted this `ConfigMap`:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: mesh-parameters
  namespace: redhat-ods-applications
  labels:
    app: model-mesh
    app.kubernetes.io/part-of: model-mesh
data:
  meshnamespace: ''
  odh-mm-rest-proxy: 'quay.io/modh/odh-mm-rest-proxy-container-live:1.20.0-model-serving-qe'
  odh-model-controller: 'quay.io/modh/odh-model-controller-container-live:1.20.0-model-serving-qe'
  odh-modelmesh: 'quay.io/modh/odh-modelmesh-container-live:1.20.0-model-serving-qe'
  odh-modelmesh-controller: >-
    quay.io/modh/odh-modelmesh-serving-controller-container-live:1.20.0-model-serving-qe
  odh-modelmesh-runtime-adapter: >-
    quay.io/modh/odh-modelmesh-runtime-adapter-container-live:1.20.0-model-serving-qe
  odh-openvino: 'quay.io/modh/odh-openvino-servingruntime-container:v1.19.0-12'
```

We might wanna take a look.
