### ISSUE TITLE
[Bug]: Error: InvalidImageName Failed to apply default image tag ":py3.8-v1": couldn't parse image reference ":py3.8-v1": invalid reference format

### ISSUE THREAD

**Issue by nnachefski** [opendatahub-io/odh-dashboard#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spinning up a default instance of ODH on OKD 4.12.0-0.okd-2023-01-21-055900.  When i attempt to Launch the notebook (from the odh-portal) i get this error on the subsequent 'jupyter-nb-nick' StatefulSet.

```
2023-01-25T05:18:45.000Z [Warning] Error: InvalidImageName
2023-01-25T05:22:26.000Z [Warning] Failed to apply default image tag ":py3.8-v1": couldn't parse image reference ":py3.8-v1": invalid reference format
```

Looking at the ImageStreams in the project, i see this (seems to be missing the IMAGE portion on each IS):

```
# oc get is
NAME                           IMAGE REPOSITORY   TAGS       UPDATED
jupyter-datascience-notebook                      py3.8-v1   30 minutes ago
jupyter-minimal-gpu-notebook                      py3.8-v1   30 minutes ago
jupyter-minimal-notebook                          py3.8-v1   30 minutes ago
jupyter-pytorch-notebook                          py3.8-v1   30 minutes ago
jupyter-tensorflow-notebook                       py3.8-v1   30 minutes ago
```

### Expected Behavior

To Launch the jupyter-minimal-notebook project

### Steps To Reproduce

This is the KFDef that i'm using to spin up the ODH cluster:

```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
  name: opendatahub
  namespace: datasci
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/cluster
      name: prometheus-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/operator
      name: prometheus-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/cluster
      name: grafana-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/grafana
      name: grafana-instance
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-notebook-controller
      name: odh-notebook-controller
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: notebook-images
      name: notebook-images
    - kustomizeConfig:
        overlays:
          - odh-model-controller
        repoRef:
          name: manifests
          path: model-mesh
      name: model-mesh
    - kustomizeConfig:
        overlays:
          - metadata-store-mariadb
          - ds-pipeline-ui
          - object-store-minio
          - default-configs
        repoRef:
          name: manifests
          path: data-science-pipelines
      name: data-science-pipelines
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.4.1'
```

### Open Data Hub Version

```yml
1.4.1
```

**Comment by nnachefski** [comment]
This was the issue, thanks!  I did not have the internal registry deployed, which was the cause of this error.  As a work-around, i just deploy the internal registry.

```
cat <<EOF | $OC_CLIENT apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  storageClassName: ${ROOK_FILE_SC}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
EOF
sleep 5

$OC_CLIENT patch config.imageregistry.operator.openshift.io cluster --type=merge -p '{"spec":{"managementState":"Managed","storage":{"pvc":{"claim":"image-registry-storage"}}}}'
```
